# TODO: Run tests against database instance. DB2 is currently not supported by TravisCI out of the box

language: node_js
dist: trusty
sudo: required

cache:
  directories:
  - "node_modules"

services:
  - docker

matrix:
  fast_finish: true
  include:
  - node_js: "11"
  - node_js: "10"
  - node_js: "8"
  - node_js: "6"

before_install:
  - docker pull ibmcom/db2express-c:10.5.0.5-3.10.0

install:
  - npm i
  - npm i ibm_db # lazy way to install the IBM ODBC driver

script:
  - npm run lint
  - npm run test-latest-knex
  - npm run test-min-knex

notifications:
  email: true